### ISSUE TITLE
The file ls command format is weird

### ISSUE THREAD

**Issue by kellrott** [ohsu-comp-bio/caliper-design#3]
The `g3t ls` output is weird:

Output looks like:
```
- meta:
    no_bucket: false
  object_id: c8d118de-ed7b-5096-b662-3eea33c5a0a4
  outs:
  - etag: cf4e249683cbe2c9a4cb9f13027bbf5a
    hash: etag
    is_symlink: false
    mime: application/octet-stream
    modified: '2024-02-24T00:56:34+00:00'
    object_id: c8d118de-ed7b-5096-b662-3eea33c5a0a4
    path: 22c46e53-2c36-4e21-848a-49693f565dfd/22c46e53-2c36-4e21-848a-49693f565dfd/TCGA-55-7913-10A-01D-A92O-36.WholeGenome.RP-1657.bai
    realpath: 22c46e53-2c36-4e21-848a-49693f565dfd/22c46e53-2c36-4e21-848a-49693f565dfd/TCGA-55-7913-10A-01D-A92O-36.WholeGenome.RP-1657.bai
    size: 9681000
  project_id: cbds-gdc_lung
- meta:
    Specimen: e477053a-32b7-422d-8d1e-fa5d3a01dd0c_specimen
    no_bucket: false
  object_id: 1c0b168f-7828-5124-a652-346699d953cc
  outs:
  - etag: bd65cf46cc4b9d9545fd327ef8c7a30e-7031
    hash: etag
    is_symlink: false
    mime: application/octet-stream
    modified: '2024-02-25T06:23:14+00:00'
    object_id: 1c0b168f-7828-5124-a652-346699d953cc
    path: e477053a-32b7-422d-8d1e-fa5d3a01dd0c/e477053a-32b7-422d-8d1e-fa5d3a01dd0c/12dd6ce5-e646-4eaa-a888-f7da0073df4c_wgs_gdc_realn.bam
    realpath: e477053a-32b7-422d-8d1e-fa5d3a01dd0c/e477053a-32b7-422d-8d1e-fa5d3a01dd0c/12dd6ce5-e646-4eaa-a888-f7da0073df4c_wgs_gdc_realn.bam
    size: 117947786324
  project_id: cbds-gdc_lung
- meta:
    no_bucket: false
  object_id: ee1ff13c-8c69-5ff8-8d0c-f222b3de3762
  outs:
  - etag: 6688cc91cfe747be0170f635dc49872e
    hash: etag
    is_symlink: false
    mime: application/octet-stream
    modified: '2024-02-25T08:35:54+00:00'
    object_id: ee1ff13c-8c69-5ff8-8d0c-f222b3de3762
    path: fed386dc-ae72-4b38-97e9-e13122223454/fed386dc-ae72-4b38-97e9-e13122223454/TCGA-L9-A7SV-10A-01D-A92T-36.WholeGenome.RP-1657.bai
    realpath: fed386dc-ae72-4b38-97e9-e13122223454/fed386dc-ae72-4b38-97e9-e13122223454/TCGA-L9-A7SV-10A-01D-A92T-36.WholeGenome.RP-1657.bai
    size: 9553864
  project_id: cbds-gdc_lung
uncommitted: []
```
